### ISSUE TITLE
Allow URL matcher to match static routes

### ISSUE THREAD

**Issue by vjik** [yiisoft/router-fastroute#88] opened 2021-12-26 14:41 UTC
For example, `Route::get('/i/{image}')->name('image')`.

**Comment by samdark** [comment] 2021-12-26 20:57
Why can't it match now?

**Comment by vjik** [comment] 2021-12-27 00:19
Static routes are ignored.
https://github.com/yiisoft/router-fastroute/blob/38258dab2c1d1d5d67ea3fa014a38aa257833a18/src/UrlMatcher.php#L203

**Comment by samdark** [comment] 2021-12-27 06:57
What would happen after a match?

**Comment by samdark** [comment] 2021-12-27 09:31
It makes no sense to match this type of routes since these are "generation-only". Let's close this issue as "by design".

**Closed by samdark** 2021-12-27 09:31 UTC
Labels: status:need more info
